server:
  port: 8087
  
spring:
  
  datasource:
     url:  jdbc:postgresql://localhost:5432/ead-athuser
     username: postgres
     password: 123456
  jpa:
    hibernate:
      ddl-auto: update 
      dialect: org.hibernate.dialect.PostreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true    
        
 
  
  
   
